
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import project.dbConnection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import project.dbConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harshit Goyal
 */
public class Supplier extends javax.swing.JFrame {
    Connection con = null;
    Statement st = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    CardLayout cardLayout;
    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Stocker.png")));
        addSupplierIdText.requestFocus();
        //fetch all data from database and store in combobox
        fetchSupplier();
        // My date and Time
        MyDate();
        MyTime();
        cardLayout = (CardLayout)(jPanel2.getLayout());
    }
    // Date function
    public void MyDate(){
        SimpleDateFormat dFormate = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel6.setText(dFormate.format(date));
    }
    
    // Time function
    public void MyTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat dFormate = new SimpleDateFormat("hh:mm:ss a");
                Date date = new Date();
                jLabel5.setText(dFormate.format(date));
            }
        }).start();
    }
    
    // add supplier reset function
    public void addSupplierReset(){
        addSupplierIdText.setText("");
        addSupplierNameText.setText("");
        addSupplierPhoneText.setText("");
        addSupplierAddressText.setText("");
        addSupplierEmailText.setText("");
    }
    
    // Fetch all Suppliers from data base and set in the como box field
    public void fetchSupplier(){
        try{
            con = dbConnection.getCon();
            String sql = "Select * from supplier";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()){
                updateSupplierIdComboBox.addItem(rs.getString("id"));
                deleteSupplierIdComboBox.addItem(rs.getString("id"));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Coonection failed: \n"+ e.getMessage());
        }finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException e) {
            }
        }
    }
    
    public void updateReset(){
        updateSupplierIdComboBox.setSelectedIndex(0);
        updateSupplierNameText.setText("");
        updateSupplierPhoneText.setText("");
        updateSupplierAddressText.setText("");
        updateSupplierEmailText.setText("");
    }
    public void deleteReset(){
        deleteSupplierIdComboBox.setSelectedIndex(0);
        deleteSupplierNameText.setText("");
        deleteSupplierPhoneText.setText("");
        deleteSupplierAddressText.setText("");
        deleteSupplierEmailText.setText("");
    }
    
    
    // fetch all data from database
    public void allSupplierRecord(){
        try {
            con = dbConnection.getCon();
            st = con.createStatement();
            rs = st.executeQuery("SELECT * from supplier");
            //allEmpRecordTable.setAutoResizeMode(allEmpRecordTable.AUTO_RESIZE_OFF);
           // Set all the content to table
           DefaultTableModel table = (DefaultTableModel) allSupplierTable.getModel();
            table.setRowCount(0);
            while(rs.next()){
                Object record[] = {
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getString("phone"),
                    rs.getString("address"),
                    rs.getString("email")
                };
                table.addRow(record);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Connection failed: \n"+ e.getMessage());
        }finally{
            try {
                st.close();
                //ps.close();
                rs.close();
            } catch (SQLException e) {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AddSupplier = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addSupplierIdText = new javax.swing.JTextField();
        addSupplierNameText = new javax.swing.JTextField();
        addSupplierAddressText = new javax.swing.JTextField();
        addSupplierEmailText = new javax.swing.JTextField();
        addSupplierAddBtn = new javax.swing.JButton();
        addSupplierPhoneText = new javax.swing.JTextField();
        addSupplierResetBtn = new javax.swing.JButton();
        Manage = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        updateSupplierIdComboBox = new javax.swing.JComboBox<>();
        updateSupplierNameText = new javax.swing.JTextField();
        updateSupplierPhoneText = new javax.swing.JTextField();
        updateSupplierAddressText = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        updateSupplierEmailText = new javax.swing.JTextField();
        updateResetBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        deleteSupplierNameText = new javax.swing.JTextField();
        deleteSupplierPhoneText = new javax.swing.JTextField();
        deleteSupplierAddressText = new javax.swing.JTextField();
        deleteSupplierIdComboBox = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        deleteSupplierEmailText = new javax.swing.JTextField();
        deleteResetBtn = new javax.swing.JButton();
        AllSupplier = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allSupplierTable = new javax.swing.JTable();
        allSupplierNameText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        allSupplierIdText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stocker");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 139, 208));

        jPanel2.setLayout(new java.awt.CardLayout());

        AddSupplier.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3), "Add Supplier", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Permanent Marker", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)), "Add New Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Supplier ID:");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 68, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Supplier Name:");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 135, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Phone Number:");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 202, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Address:");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Email ID:");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 337, -1, -1));

        addSupplierIdText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel10.add(addSupplierIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 65, 184, -1));

        addSupplierNameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel10.add(addSupplierNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 132, 184, -1));

        addSupplierAddressText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel10.add(addSupplierAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 267, 184, -1));

        addSupplierEmailText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel10.add(addSupplierEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 334, 184, -1));

        addSupplierAddBtn.setBackground(new java.awt.Color(102, 187, 0));
        addSupplierAddBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addSupplierAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSupplierAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/AddBtn.png"))); // NOI18N
        addSupplierAddBtn.setText("Add");
        addSupplierAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierAddBtnActionPerformed(evt);
            }
        });
        jPanel10.add(addSupplierAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 413, -1, -1));

        addSupplierPhoneText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel10.add(addSupplierPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 199, 184, -1));

        addSupplierResetBtn.setBackground(new java.awt.Color(223, 77, 96));
        addSupplierResetBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addSupplierResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSupplierResetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/clear.png"))); // NOI18N
        addSupplierResetBtn.setText("Clear");
        addSupplierResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierResetBtnActionPerformed(evt);
            }
        });
        jPanel10.add(addSupplierResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 413, -1, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AddSupplierLayout = new javax.swing.GroupLayout(AddSupplier);
        AddSupplier.setLayout(AddSupplierLayout);
        AddSupplierLayout.setHorizontalGroup(
            AddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddSupplierLayout.setVerticalGroup(
            AddSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(AddSupplier, "AddSupplier");

        Manage.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3), "Manage Supplier", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Permanent Marker", 0, 36), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)), "Udate Existing Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Supplier ID:");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 68, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Supplier Name:");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 129, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Phone Number:");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 191, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Address:");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 253, -1, -1));

        updateSupplierIdComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateSupplierIdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Supplier" }));
        updateSupplierIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSupplierIdComboBoxActionPerformed(evt);
            }
        });
        jPanel11.add(updateSupplierIdComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 65, 230, -1));

        updateSupplierNameText.setEditable(false);
        updateSupplierNameText.setBackground(new java.awt.Color(255, 255, 255));
        updateSupplierNameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel11.add(updateSupplierNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 126, 230, -1));

        updateSupplierPhoneText.setEditable(false);
        updateSupplierPhoneText.setBackground(new java.awt.Color(255, 255, 255));
        updateSupplierPhoneText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel11.add(updateSupplierPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 188, 230, -1));

        updateSupplierAddressText.setEditable(false);
        updateSupplierAddressText.setBackground(new java.awt.Color(255, 255, 255));
        updateSupplierAddressText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel11.add(updateSupplierAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 250, 230, -1));

        updateBtn.setBackground(new java.awt.Color(102, 187, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/AddBtn.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel11.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 399, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Email ID:");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 314, -1, -1));

        updateSupplierEmailText.setEditable(false);
        updateSupplierEmailText.setBackground(new java.awt.Color(255, 255, 255));
        updateSupplierEmailText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel11.add(updateSupplierEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 311, 230, -1));

        updateResetBtn.setBackground(new java.awt.Color(223, 77, 96));
        updateResetBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateResetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/clear.png"))); // NOI18N
        updateResetBtn.setText("Clear");
        updateResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResetBtnActionPerformed(evt);
            }
        });
        jPanel11.add(updateResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 399, -1, -1));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 55, 453, 486));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)), "Delete Existing Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Supplier ID:");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 68, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Supplier Name:");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 129, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Phone Number:");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 190, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Address:");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 251, -1, -1));

        deleteSupplierNameText.setEditable(false);
        deleteSupplierNameText.setBackground(new java.awt.Color(255, 255, 255));
        deleteSupplierNameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel12.add(deleteSupplierNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 126, 184, -1));

        deleteSupplierPhoneText.setEditable(false);
        deleteSupplierPhoneText.setBackground(new java.awt.Color(255, 255, 255));
        deleteSupplierPhoneText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel12.add(deleteSupplierPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 187, 184, -1));

        deleteSupplierAddressText.setEditable(false);
        deleteSupplierAddressText.setBackground(new java.awt.Color(255, 255, 255));
        deleteSupplierAddressText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel12.add(deleteSupplierAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 248, 184, -1));

        deleteSupplierIdComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteSupplierIdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Supplier" }));
        deleteSupplierIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupplierIdComboBoxActionPerformed(evt);
            }
        });
        jPanel12.add(deleteSupplierIdComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 65, 184, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 54, 54));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Delete.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel12.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 399, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Email ID:");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 312, -1, -1));

        deleteSupplierEmailText.setEditable(false);
        deleteSupplierEmailText.setBackground(new java.awt.Color(255, 255, 255));
        deleteSupplierEmailText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel12.add(deleteSupplierEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 309, 184, -1));

        deleteResetBtn.setBackground(new java.awt.Color(223, 77, 96));
        deleteResetBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteResetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/clear.png"))); // NOI18N
        deleteResetBtn.setText("Clear");
        deleteResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResetBtnActionPerformed(evt);
            }
        });
        jPanel12.add(deleteResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 399, -1, -1));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 55, 481, 486));

        javax.swing.GroupLayout ManageLayout = new javax.swing.GroupLayout(Manage);
        Manage.setLayout(ManageLayout);
        ManageLayout.setHorizontalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageLayout.setVerticalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Manage, "Manage");

        AllSupplier.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3), "All Supplier", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Permanent Marker", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        allSupplierTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        allSupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Supplier Phone No.", "Address", "Email ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allSupplierTable.setRowHeight(26);
        allSupplierTable.setRowMargin(3);
        jScrollPane1.setViewportView(allSupplierTable);
        if (allSupplierTable.getColumnModel().getColumnCount() > 0) {
            allSupplierTable.getColumnModel().getColumn(0).setMinWidth(50);
            allSupplierTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            allSupplierTable.getColumnModel().getColumn(0).setMaxWidth(200);
            allSupplierTable.getColumnModel().getColumn(1).setMinWidth(100);
            allSupplierTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            allSupplierTable.getColumnModel().getColumn(1).setMaxWidth(250);
            allSupplierTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            allSupplierTable.getColumnModel().getColumn(3).setPreferredWidth(300);
        }

        allSupplierNameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        allSupplierNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                allSupplierNameTextKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Supplier Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Supplier ID:");

        allSupplierIdText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        allSupplierIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                allSupplierIdTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(allSupplierIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(allSupplierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allSupplierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(allSupplierIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AllSupplierLayout = new javax.swing.GroupLayout(AllSupplier);
        AllSupplier.setLayout(AllSupplierLayout);
        AllSupplierLayout.setHorizontalGroup(
            AllSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AllSupplierLayout.setVerticalGroup(
            AllSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(AllSupplier, "AllSupplier");

        jPanel3.setBackground(new java.awt.Color(0, 124, 197));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Permanent Marker", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/AddItem.png"))); // NOI18N
        jLabel1.setText("Add Supplier");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jPanel4.setBackground(new java.awt.Color(0, 124, 197));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Permanent Marker", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/AddItem.png"))); // NOI18N
        jLabel2.setText("Manage Supplier");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        jPanel5.setBackground(new java.awt.Color(0, 124, 197));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Permanent Marker", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/AddItem.png"))); // NOI18N
        jLabel3.setText("All Supplier");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stocker");

        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time");

        jLabel6.setFont(new java.awt.Font("Engravers MT", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back_1.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/supplier new.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(308, 308, 308)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // Add Item Button
        cardLayout.show(jPanel2, "AddSupplier");
        // reset all fields of Add Supplier Panel
        addSupplierReset();
        addSupplierIdText.requestFocus();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(0,91,147));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(0,124,197));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // Manage Items Button
        cardLayout.show(jPanel2, "Manage");
        // reset all fields
        deleteReset();
        updateReset();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(0,91,147));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(0,124,197));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // All Stock Button
        cardLayout.show(jPanel2, "AllSupplier");
        //Reset fiesls
        allSupplierIdText.setText("");
        allSupplierNameText.setText("");
        
        // fetch all record from database into table
        allSupplierRecord();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(0,91,147));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(0,124,197));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // Back Button
        dispose();
        new MainPage().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void addSupplierResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierResetBtnActionPerformed
        // Add Supplier Reset Button
        addSupplierReset();
        addSupplierIdText.requestFocus();
    }//GEN-LAST:event_addSupplierResetBtnActionPerformed

    private void addSupplierAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierAddBtnActionPerformed
        // Add Supplier Add Button
        String id = addSupplierIdText.getText();
        String name = addSupplierNameText.getText();
        String phone = addSupplierPhoneText.getText();
        String address = addSupplierAddressText.getText();
        String email = addSupplierEmailText.getText();
        try {
            con = dbConnection.getCon();
            ps = con.prepareStatement("insert into supplier values(?,?,?,?,?)");
            ps.setString(1, id);
            ps.setString(2, name);
            ps.setString(3, phone);
            ps.setString(4, address);
            ps.setString(5, email);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Sucessfully saved");
            addSupplierReset();
            addSupplierIdText.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed: \n" +e.getMessage());
        }finally{
            try {
                ps.close();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_addSupplierAddBtnActionPerformed

    private void allSupplierIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allSupplierIdTextKeyReleased
        // All Supplier Filter By ID
        if(allSupplierIdText.getText().equals("")){ 
            allSupplierRecord();
        }
        else
        try {
            String id = allSupplierIdText.getText();
            con = dbConnection.getCon();
            st = con.createStatement();
            rs = st.executeQuery("SELECT * from supplier where id ='"+id+"'");
            //allEmpRecordTable.setAutoResizeMode(allEmpRecordTable.AUTO_RESIZE_OFF); // to make  down scroll bar in table 
            // Set all the content to table
            DefaultTableModel table = (DefaultTableModel) allSupplierTable.getModel();
            table.setRowCount(0);
            while(rs.next()){
                Object record[] = {
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getString("phone"),
                    rs.getString("address"),
                    rs.getString("email")
                };
                table.addRow(record);
            }
        } catch (SQLException e) {
           
            JOptionPane.showMessageDialog(null, "Connection failed: \n"+e.getMessage());
        }finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_allSupplierIdTextKeyReleased

    private void allSupplierNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allSupplierNameTextKeyReleased
        // All Supplier Filter By Name
        if(allSupplierNameText.getText().equals("")){ 
            allSupplierRecord();
        }
        else
        try {
            String name = allSupplierNameText.getText();
            con = dbConnection.getCon();
            st = con.createStatement();
            rs = st.executeQuery("SELECT * from supplier where name ='"+name+"'");
            //allEmpRecordTable.setAutoResizeMode(allEmpRecordTable.AUTO_RESIZE_OFF); // to make  down scroll bar in table 
            // Set all the content to table
            DefaultTableModel table = (DefaultTableModel) allSupplierTable.getModel();
            table.setRowCount(0);
            while(rs.next()){
                Object record[] = {
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getString("phone"),
                    rs.getString("address"),
                    rs.getString("email")
                };
                table.addRow(record);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed: \n"+e.getMessage());
        }finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_allSupplierNameTextKeyReleased

    private void updateResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResetBtnActionPerformed
        // Update Panel reset button
        updateReset();
        
    }//GEN-LAST:event_updateResetBtnActionPerformed

    private void deleteResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResetBtnActionPerformed
        // Delete Reset
        deleteReset();
    }//GEN-LAST:event_deleteResetBtnActionPerformed

    private void updateSupplierIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplierIdComboBoxActionPerformed
        // Update pannel Supplier id combo box
        if(updateSupplierIdComboBox.getSelectedItem().toString().equals("Select Supplier")){
            updateReset();
            updateSupplierNameText.setEditable(false);
            updateSupplierPhoneText.setEditable(false);
            updateSupplierAddressText.setEditable(false);
            updateSupplierEmailText.setEditable(false);
        }else{
            try{
            String id = updateSupplierIdComboBox.getSelectedItem().toString();
            con = dbConnection.getCon();
            st = con.createStatement();
            rs = st.executeQuery("Select * from supplier where id='"+id+"'");

            updateSupplierNameText.setEditable(true);
            updateSupplierPhoneText.setEditable(true);
            updateSupplierAddressText.setEditable(true);
            updateSupplierEmailText.setEditable(true);
            
            //.setText(rs.getString(1));
            updateSupplierNameText.setText(rs.getString(2));
            updateSupplierPhoneText.setText(rs.getString(3));
            updateSupplierAddressText.setText(rs.getString(4));
            updateSupplierEmailText.setText(rs.getString(5));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed: \n" + e.getMessage());
        }finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException e) {
            }
            }
        }
    }//GEN-LAST:event_updateSupplierIdComboBoxActionPerformed

    private void deleteSupplierIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupplierIdComboBoxActionPerformed
        // Delete pannel Supplier id combo box
        if(deleteSupplierIdComboBox.getSelectedItem().toString().equals("Select Supplier")){
            deleteReset();
        }else{
            try{
            String id = deleteSupplierIdComboBox.getSelectedItem().toString();
            con = dbConnection.getCon();
            st = con.createStatement();
            rs = st.executeQuery("Select * from supplier where id='"+id+"'");
            //.setText(rs.getString(1));
            deleteSupplierNameText.setText(rs.getString(2));
            deleteSupplierPhoneText.setText(rs.getString(3));
            deleteSupplierAddressText.setText(rs.getString(4));
            deleteSupplierEmailText.setText(rs.getString(5));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed: \n" + e.getMessage());
        }finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException e) {
            }
            }
        }
    }//GEN-LAST:event_deleteSupplierIdComboBoxActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // Update Button in manage Supplier Pannel
        String id = updateSupplierIdComboBox.getSelectedItem().toString();
        String name = updateSupplierNameText.getText();
        String phone = updateSupplierPhoneText.getText();
        String address = updateSupplierAddressText.getText();
        String email = updateSupplierEmailText.getText();
        try {
            con = dbConnection.getCon();
            ps = con.prepareStatement("update supplier set name=?, phone=?, address=?, email=? where id='"+ id +"'");
            ps.setString(1, name);
            ps.setString(2, phone);
            ps.setString(3, address);
            ps.setString(4, email);

            int response = JOptionPane.showConfirmDialog(null, "Do you want to sure to update?", "select", JOptionPane.YES_NO_OPTION);
            if(response == JOptionPane.YES_OPTION){

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully updated"); 
            }
            updateReset();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Connection failed: \n"+ e.getMessage());
        }finally{
            try {
                ps.close();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // Delete Button in Manage Supplier Panel
        String id = deleteSupplierIdComboBox.getSelectedItem().toString();
        try {
            con = dbConnection.getCon();
            ps = con.prepareStatement("delete from supplier where id='"+id+"'");
            int response = JOptionPane.showConfirmDialog(null, "Do you want to sure to delete?", "select", JOptionPane.YES_NO_OPTION);
            if(response == JOptionPane.YES_OPTION){
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete record sucessfylly");
                deleteReset();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection failed: \n"+e.getMessage());
        }finally{
            try {
                ps.close();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddSupplier;
    private javax.swing.JPanel AllSupplier;
    private javax.swing.JPanel Manage;
    private javax.swing.JButton addSupplierAddBtn;
    private javax.swing.JTextField addSupplierAddressText;
    private javax.swing.JTextField addSupplierEmailText;
    private javax.swing.JTextField addSupplierIdText;
    private javax.swing.JTextField addSupplierNameText;
    private javax.swing.JTextField addSupplierPhoneText;
    private javax.swing.JButton addSupplierResetBtn;
    private javax.swing.JTextField allSupplierIdText;
    private javax.swing.JTextField allSupplierNameText;
    private javax.swing.JTable allSupplierTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteResetBtn;
    private javax.swing.JTextField deleteSupplierAddressText;
    private javax.swing.JTextField deleteSupplierEmailText;
    private javax.swing.JComboBox<String> deleteSupplierIdComboBox;
    private javax.swing.JTextField deleteSupplierNameText;
    private javax.swing.JTextField deleteSupplierPhoneText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateResetBtn;
    private javax.swing.JTextField updateSupplierAddressText;
    private javax.swing.JTextField updateSupplierEmailText;
    private javax.swing.JComboBox<String> updateSupplierIdComboBox;
    private javax.swing.JTextField updateSupplierNameText;
    private javax.swing.JTextField updateSupplierPhoneText;
    // End of variables declaration//GEN-END:variables
}
